// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqCAXz_Uz1aQGdRAyIzrdo4H9hpHVU84E',
    appId: '1:966643038975:android:26aec247032de77df7eaca',
    messagingSenderId: '966643038975',
    projectId: 'blindly-9d3a7',
    databaseURL: 'https://blindly-9d3a7-default-rtdb.firebaseio.com',
    storageBucket: 'blindly-9d3a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl1C52U1nr7tGjKpPhxYoWk-SlLknR9yY',
    appId: '1:966643038975:ios:8a3b62f42830ee5ff7eaca',
    messagingSenderId: '966643038975',
    projectId: 'blindly-9d3a7',
    databaseURL: 'https://blindly-9d3a7-default-rtdb.firebaseio.com',
    storageBucket: 'blindly-9d3a7.firebasestorage.app',
    iosBundleId: 'com.example.blindly',
  );
}
