// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCm4dWP05VDM_7m0E86bLU9uqW5ZlTQcc',
    appId: '1:1064511627841:web:5bfa1c996c8c94dd341cc0',
    messagingSenderId: '1064511627841',
    projectId: 'blindly-807b1',
    authDomain: 'blindly-807b1.firebaseapp.com',
    storageBucket: 'blindly-807b1.firebasestorage.app',
    measurementId: 'G-H1WCTJQNQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh39gDXHU5QfZYoOPOtpYlOSC3JEGKO1U',
    appId: '1:1064511627841:android:a6e723ea24e344fa341cc0',
    messagingSenderId: '1064511627841',
    projectId: 'blindly-807b1',
    storageBucket: 'blindly-807b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXoC_Ph9jwafuGYl_Hp5uobH9IQzQd1jA',
    appId: '1:1064511627841:ios:cc342627a4f01b3c341cc0',
    messagingSenderId: '1064511627841',
    projectId: 'blindly-807b1',
    storageBucket: 'blindly-807b1.firebasestorage.app',
    iosBundleId: 'com.example.blindly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXoC_Ph9jwafuGYl_Hp5uobH9IQzQd1jA',
    appId: '1:1064511627841:ios:cc342627a4f01b3c341cc0',
    messagingSenderId: '1064511627841',
    projectId: 'blindly-807b1',
    storageBucket: 'blindly-807b1.firebasestorage.app',
    iosBundleId: 'com.example.blindly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCm4dWP05VDM_7m0E86bLU9uqW5ZlTQcc',
    appId: '1:1064511627841:web:a7aceab3841276e8341cc0',
    messagingSenderId: '1064511627841',
    projectId: 'blindly-807b1',
    authDomain: 'blindly-807b1.firebaseapp.com',
    storageBucket: 'blindly-807b1.firebasestorage.app',
    measurementId: 'G-W6SGHKWW9M',
  );
}
