const Map<String, String> labelDescriptions = {
  'person': 'There is a person ahead',
  'bicycle': 'A bicycle is nearby',
  'car': 'A car is ahead, be careful',
  'motorcycle': 'A motorcycle is approaching',
  'airplane': 'An airplane is in the sky',
  'bus': 'A bus is ahead',
  'train': 'A train is nearby',
  'truck': 'A truck is on your path',
  'boat': 'A boat is nearby',
  'traffic light': 'A traffic light is ahead',
  'fire hydrant': 'A fire hydrant is nearby',
  'stop sign': 'A stop sign is ahead',
  'parking meter': 'A parking meter is ahead',
  'bench': 'A bench is in front of you',
  'bird': 'A bird is nearby',
  'cat': 'A cat is near you',
  'dog': 'Careful, a dog is ahead',
  'horse': 'A horse is detected nearby',
  'sheep': 'A sheep is nearby',
  'cow': 'A cow is ahead',
  'elephant': 'An elephant is nearby',
  'bear': 'A bear is detected, be cautious',
  'zebra': 'A zebra is nearby',
  'giraffe': 'A giraffe is nearby',
  'backpack': 'Someone with a backpack is nearby',
  'umbrella': 'Someone is carrying an umbrella',
  'handbag': 'A handbag is nearby',
  'tie': 'A person with a tie is detected',
  'suitcase': 'A suitcase is ahead',
  'frisbee': 'A frisbee is nearby',
  'skis': 'Skis are detected',
  'snowboard': 'A snowboard is nearby',
  'sports ball': 'A sports ball is nearby',
  'kite': 'A kite is in the sky',
  'baseball bat': 'A baseball bat is detected',
  'baseball glove': 'A baseball glove is nearby',
  'skateboard': 'A skateboard is ahead',
  'surfboard': 'A surfboard is nearby',
  'tennis racket': 'A tennis racket is detected',
  'bottle': 'A bottle is ahead',
  'wine glass': 'A wine glass is nearby',
  'cup': 'A cup is ahead',
  'fork': 'A fork is nearby',
  'knife': 'A knife is ahead, be careful',
  'spoon': 'A spoon is nearby',
  'bowl': 'A bowl is ahead',
  'banana': 'A banana is nearby',
  'apple': 'An apple is nearby',
  'sandwich': 'A sandwich is nearby',
  'orange': 'An orange is nearby',
  'broccoli': 'Broccoli is nearby',
  'carrot': 'A carrot is nearby',
  'hot dog': 'A hot dog is nearby',
  'pizza': 'A pizza is ahead',
  'donut': 'A donut is nearby',
  'cake': 'A cake is nearby',
  'chair': 'A chair is in front of you',
  'couch': 'A couch is ahead',
  'potted plant': 'A potted plant is ahead',
  'bed': 'A bed is ahead',
  'dining table': 'A dining table is ahead',
  'toilet': 'A toilet is ahead',
  'tv': 'A television is ahead',
  'laptop': 'A laptop is ahead',
  'mouse': 'A computer mouse is nearby',
  'remote': 'A remote control is nearby',
  'keyboard': 'A keyboard is nearby',
  'cell phone': 'A cellphone is nearby',
  'microwave': 'A microwave is ahead',
  'oven': 'An oven is ahead',
  'toaster': 'A toaster is nearby',
  'sink': 'A sink is ahead',
  'refrigerator': 'A refrigerator is ahead',
  'book': 'A book is nearby',
  'clock': 'A clock is ahead',
  'vase': 'A vase is nearby',
  'scissors': 'Scissors are nearby, be careful',
  'teddy bear': 'A teddy bear is nearby',
  'hair drier': 'A hair dryer is nearby',
  'toothbrush': 'A toothbrush is nearby',
};

String getLabelDescription(String label) {
  if (labelDescriptions.containsKey(label)) {
    return labelDescriptions[label]!;
  }
  return 'Detected $label';
}